### ISSUE TITLE
unlock deps for 1.6.x

### ISSUE THREAD

**Issue by mathieujobin** [redis-store/redis-rack#24] opened 2017-04-11 21:07 UTC
Hello @tubbo 

if you could release 1.6.1 with this small fix

https://github.com/venuenext/redis-rack/commit/5924cbe7afccf8614c35bd17c4440b074f173a50

this is all I need to use redis-activesupport 5.0.2 and all the redis-* 5.x on a rails 4.2 app

this is what I am using now 

```
gem 'redis', '~> 3.1.0'
gem 'redis-store', '~> 1.3.0'
gem 'redis-activesupport', '~> 5.0.2'
gem 'redis-actionpack', '~> 5.0.1'
gem 'redis-namespace'
gem 'redis-rails', '~> 5.0.2'
gem 'redis-rack', github: 'venuenext/redis-rack', branch: '1.6.x'
gem 'redis-rack-cache'
```

thanks

**Comment by tubbo** [comment] 2017-04-13 15:43
@mathieujobin this looks like a regression of some kind. running tests with the gem on both versions seemed to pass, so **v2.0.2** is released with relaxed deps.

**Closed by tubbo** 2017-04-13 15:43 UTC
